# This workflow will try to compile, test and build a temporary jar
name: CI_CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Verify_deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # so we can run maven commands later
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # for debugging
      - run: pwd
      - run: ls
      # Verify will run all the lifecycle goals leading up to verify (compile, tests, package, etc.)
      - name: Verify and build with Maven
        run: mvn --batch-mode --update-snapshots verify
      # DEPLOYMENT PART WITH DOCKER
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # for debugging
      - run: pwd
      - run: ls
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: /home/runner/work/java_spring_boot_scrum/java_spring_boot_scrum
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scrum_backend_java:latest
     # - name: Deploy on azure VM
      #  uses: fjogeleit/http-request-action@master
      #  with:
      #    url: '40.118.126.237:2999/update?key=123'
      #    method: 'POST'
      #    username: ${{ secrets.AWX_USER }}
      #    password: ${{ secrets.AWX_PASSWORD }}
